### ISSUE TITLE
Github / npm hoek version mismatch

### ISSUE THREAD

**Issue by johnbrett** [hapijs/pez#10]
I see in the `package.json` here that `hoek` is set to 4.x.x, but when I install `pez`, I get `hoek`@3.0.4. 

![image](https://cloud.githubusercontent.com/assets/4015939/15357113/b7eec5f4-1cf4-11e6-828b-091b04ba02c9.png)

Does the version on npm need to be updated to use hoek@4.x.x as well?

**Comment by cjihrig** [comment]
Closed in 3222197175f464ed5d8c6df0b49e2155eae6fabc.
