### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by MarkTraceur** [hapijs/pez#7]
Nothing else to say, really. How do I use this library? How do I install it? What are its limitations? I don't even know which of those questions are relevant because I know nothing about this library and I don't have time to dig through all of your code to find it all out for myself.

**Comment by hueniverse** [comment]
Don't use it! Problem solved.

**Comment by djensen47** [comment]
@MarkTraceur You should probably ask your question here: https://github.com/hapijs/discuss/issues

I recommend simplifying your question to a simple "What does Pez do?"
